
TEXTS={
"ru":{
"welcome":"<b>Добро пожаловать в SpecTech</b>\n\nЗакажите спецтехнику с нужными характеристиками.",
"language_saved":"Русский выбран.",
"choose_equipment":"Выберите тип техники:",
"selected_equipment":"Выбрано: <b>{category}</b>",
"enter_location":"Отправьте текущую геолокацию объекта кнопкой ниже.",
"need_phone":"Для оформления заказов нужен ваш номер телефона. Нажмите кнопку ниже и отправьте контакт.",
"location_received":"Геолокация получена.",
"choose_date":"Нажмите кнопку ниже, чтобы выбрать дату:",
"choose_time":"Нажмите кнопку ниже, чтобы выбрать время:",
"choose_payment":"Выберите способ оплаты:",
"payment_card":"💳 Картой",
"payment_cash":"💵 Наличными",
"comment":"",
"no_comment":"Без дополнительных требований",
"confirm":"<b>Проверьте заказ</b>\n\nТехника: {category}\n{specs}\nДата: {date}\nВремя: {time}\nМесто: геолокация получена\nОплата: {payment}",
"order_created":"<b>Заказ #{id} создан.</b>\n\n{details}\n\nИщем свободную технику, которая подходит по характеристикам.",
"no_match":"Сейчас подходящей свободной техники нет.\n\nЗаказ <b>#{id}</b> сохранён. Как только подходящая техника освободится, заказчик получит уведомление автоматически.",
"match_found":"<b>Нашлась подходящая техника для заказа #{id}.</b>\n\nВладелец уже получил уведомление.",
"new_order":"<b>Новый подходящий заказ #{id}</b>\n\nТехника: {category}\n{specs}\nДата и время: {date_time}\n📍 Координаты объекта получены\nЦена вашей техники: {price} сум/ч\nОплата заказчика: {payment}\nТелефон заказчика: <code>{customer_phone}</code>",
"owner_busy":"У вас уже есть активный заказ. Новый заказ можно принять только после завершения текущего объекта и подтверждения обеих сторон.",
"order_taken":"Этот заказ уже принят другим владельцем.",
"order_accepted_owner":"Заказ #{id} принят.\n\nКогда обе стороны нажмут «Начать работу», запустится таймер фактической работы.",
"customer_accepted":"<b>Заказ #{id} принят.</b>\n\nТехника: {category}\n{specs}\nМарка: {brand}\nНомер: {plate}\nЦена: {price} сум/ч\nТелефон владельца: <code>{owner_phone}</code>\n\nНажмите «Начать работу». Таймер начнётся только после подтверждения обеих сторон.",
"complete_owner":"Когда работа на объекте действительно закончена, нажмите кнопку ниже.",
"complete_customer":"Если работа действительно завершена, подтвердите завершение.",
"completion_wait":"Ваше подтверждение сохранено. Ждём подтверждение второй стороны.",
"order_completed":"<b>Заказ #{id} полностью завершён.</b>\n\nВладелец и заказчик подтвердили окончание. Техника снова свободна.",
"start_confirmed":"Ваше подтверждение начала работы сохранено. Ждём вторую сторону.",
"start_wait":"Заказ #{id}: вторая сторона должна нажать «Начать работу».\nТаймер ещё не запущен.",
"work_started":"<b>Работа по заказу #{id} началась.</b>\nЦена: {price} сум/ч\n\n⏱ Таймер запущен. После окончания обе стороны нажимают «Завершить объект».",
"timer_live":"<b>Заказ #{id} — работа идёт</b>\n\n⏱ Фактическое время: <b>{elapsed}</b>\n💰 Текущая стоимость: <b>{amount} сум</b>\nЦена: {price} сум/ч",
"work_finished":"<b>Заказ #{id}: работа завершена.</b>\n\n⏱ Фактическое время: <b>{elapsed}</b>\nЦена: {price} сум/ч\n💰 Стоимость работы: <b>{amount} сум</b>\n📊 Комиссия сервиса 5%: <b>{commission} сум</b>",
"card_payment":"<b>Оплата заказа #{id}</b>\n\nК оплате: <b>{amount} сум</b>\nПолучатель: <b>{recipient}</b>\nКарта: <code>{card}</code>\n\nПосле перевода сообщите боту о произведённой оплате.",
"enter_owner_card":"Введите номер карты, на которую заказчики смогут оплачивать работу вашей техники. Только цифры, 12–19 знаков.",
"card_error":"Введите корректный номер карты (12–19 цифр).",
"owner_payment_blocked":"Новые заказы недоступны: у вас есть неоплаченная комиссия сервиса. Сначала оплатите её.",
"owner_card_required":"Для заказов с оплатой картой сначала добавьте карту владельца в систему.",
"customer_payment_card":"<b>Оплата заказа #{id}</b>\n\nК оплате: <b>{amount} сум</b>\nКарта владельца техники: <code>{card}</code>\n\nПереведите указанную сумму владельцу и затем нажмите «Я оплатил».",
"customer_payment_cash":"<b>Оплата заказа #{id}</b>\n\nК оплате наличными владельцу техники: <b>{amount} сум</b>\n\nПередайте деньги водителю и затем нажмите «Я оплатил».",
"customer_payment_missing_card":"У владельца не указана карта. Свяжитесь с поддержкой для оплаты.",
"owner_waiting_payment":"Заказ #{id} завершён.\n\nСтоимость: <b>{amount} сум</b>\n\n⏳ Ожидаем подтверждение оплаты от заказчика.",
"owner_confirm_payment":"Заказчик отметил, что оплатил заказ #{id}.\n\nСумма: <b>{amount} сум</b>\n\nЕсли деньги действительно получены, подтвердите получение.",
"customer_payment_sent":"Ваше подтверждение оплаты отправлено владельцу. Ждём его подтверждение получения.",
"customer_payment_confirmed":"Оплата заказа #{id} подтверждена обеими сторонами.",
"owner_commission_due":"Оплата заказа #{id} подтверждена.\n\nВаша комиссия сервису: <b>{commission} сум</b> (5%).\n\nПереведите комиссию на карту сервиса:\nПолучатель: <b>{recipient}</b>\nКарта: <code>{card}</code>\n\nПосле перевода нажмите «Я оплатил комиссию». Пока администратор не подтвердит платёж, новые заказы недоступны.",
"commission_paid_ok":"Комиссия подтверждена администратором. Новые заказы снова доступны.",
"commission_wait_admin":"Платёж комиссии отправлен администратору на проверку. До подтверждения новые заказы недоступны.",
"commission_rejected":"Администратор не подтвердил платёж комиссии. Проверьте перевод и отправьте комиссию ещё раз.",
"admin_customer_payment":"🔔 <b>Проверка оплаты заказа #{id}</b>\n\nСумма: <b>{amount} сум</b>\nЗаказчик: <code>{customer}</code>\nСпособ: {method}\n\nПроверьте поступление в банке и подтвердите или отклоните.",
"customer_payment_rejected":"Оплата заказа #{id} пока не подтверждена администратором. Проверьте перевод на сумму <b>{amount} сум</b> и нажмите «Я оплатил» ещё раз после корректного платежа.",
"admin_commission":"💳 <b>Проверка комиссии #{id}</b>\n\nВодитель: <code>{owner}</code>\nКомиссия: <b>{commission} сум</b>\nКарта сервиса: <code>{card}</code>\n\nВодитель отметил, что перевёл комиссию. Проверьте банк и подтвердите.",
"payment_unavailable":"Этот платёж сейчас нельзя подтвердить.",
"commission_unavailable":"Комиссию сейчас нельзя подтвердить как оплаченную.",
"cash_commission":"Заказ #{id} оплачен наличными заказчику.\n\nСтоимость работы: {amount} сум\nВаша комиссия сервису (5%): <b>{commission} сум</b>\n\nПожалуйста, переведите комиссию сервису.",
"equipment_freed":"Техника снова свободна.",
"no_orders":"Заказов пока нет.",
"my_orders_title":"<b>Мои заказы</b>\n\n",
"order_list_item":"#{id} • {category} • {status} • {date_time}\n",
"profile":"<b>Профиль</b>\n\nИмя: {name}\nTelegram ID: <code>{telegram_id}</code>\nТелефон: <code>{phone}</code>",
"support":"Поддержка: свяжитесь с администратором проекта.",
"owner_card_saved":"Карта сохранена. Теперь заказчики смогут оплачивать вашу работу на неё.",
"owner_card_title":"<b>Карта владельца</b>\n\nТекущая карта: <code>{card}</code>",
"owner_intro":"<b>Кабинет владельца техники</b>\n\nДобавьте технику. После проверки администратора она будет получать подходящие заказы.",
"owner_choose":"Выберите тип техники:",
"enter_brand":"Введите марку и модель.",
"enter_plate":"Введите государственный номер.",
"enter_year":"Введите год выпуска.",
"year_error":"Введите корректный год.",
"enter_price":"Введите цену за час в сумах.",
"price_error":"Введите цену числом.",
"equipment_added":"Техника #{id} отправлена администратору на проверку.",
"my_equipment_title":"<b>Моя техника</b>\n\n",
"equipment_item":"#{id} • {category}\nМарка: {brand}\nНомер: {plate}\n{specs}\nЦена: {price} сум/ч\nСтатус: {status} | Проверка: {verification}\n\n",
"admin_panel":"<b>Админ-панель</b>\n\nТехника на проверке: {count}",
"admin_equipment":"<b>Техника на проверке</b>\n\n#{id} • {category}\nМарка: {brand}\nНомер: {plate}\nВладелец: <code>{owner}</code>\n{specs}\nЦена: {price} сум/ч",
"approved":"Техника #{id} одобрена.",
"rejected":"Техника #{id} отклонена.",
"equipment_approved_owner":"<b>Техника #{id} одобрена.</b> Она может получать подходящие заказы.",
"equipment_rejected_owner":"Техника #{id} не прошла проверку.",
"flow_cancelled":"Действие отменено.",
"session_expired":"Сессия истекла. Начните заново.",
"no_pending":"Техники на проверке нет."
},
"uz":{
"welcome":"<b>SpecTech'ga xush kelibsiz</b>\n\nKerakli xususiyatlarga ega maxsus texnikani buyurtma qiling.",
"language_saved":"O'zbekcha tanlandi.","choose_equipment":"Texnika turini tanlang:","selected_equipment":"Tanlandi: <b>{category}</b>",
"enter_location":"Obyektning joriy geolokatsiyasini pastdagi tugma orqali yuboring.",
"need_phone":"Buyurtmalar uchun telefon raqamingiz kerak. Pastdagi tugma orqali kontaktingizni yuboring.","location_received":"Geolokatsiya olindi.","choose_date":"Quyidagi tugma orqali sanani tanlang:","choose_time":"Quyidagi tugma orqali vaqtni tanlang:","choose_payment":"To'lov usulini tanlang:","payment_card":"💳 Karta", "payment_cash":"💵 Naqd","comment":"Buyurtmaga qo'shimcha talablar bormi?","no_comment":"Qo'shimcha talab yo'q",
"confirm":"<b>Buyurtmani tekshiring</b>\n\nTexnika: {category}\n{specs}\nSana: {date}\nVaqt: {time}\nJoy: geolokatsiya olindi\nTo'lov: {payment}",
"order_created":"<b>#{id} buyurtma yaratildi.</b>\n\n{details}\n\nXususiyatlarga mos bo'sh texnika qidirilmoqda.","no_match":"Hozir mos bo'sh texnika yo'q.\n\n#{id} buyurtma saqlandi. Mos texnika bo'shashi bilan sizga darhol xabar beramiz.","match_found":"<b>#{id} buyurtma uchun mos texnika topildi.</b>\n\nEgasi xabardor qilindi.",
"new_order":"<b>#{id} yangi mos buyurtma</b>\n\nTexnika: {category}\n{specs}\nSana va vaqt: {date_time}\n📍 Obyekt koordinatalari olindi\nSizning texnikangiz narxi: {price} so'm/soat\nBuyurtmachi to'lovi: {payment}",
"owner_busy":"Sizda faol buyurtma bor. Joriy obyekt tugab, ikkala tomon tasdiqlagandan keyingina yangi buyurtma olish mumkin.","order_taken":"Bu buyurtmani boshqa egasi qabul qilgan.","order_accepted_owner":"#{id} buyurtma qabul qilindi.\n\nIkkala tomon «Ishni boshlash»ni bosgandan keyin taymer ishga tushadi.",
"customer_accepted":"<b>#{id} buyurtma qabul qilindi.</b>\n\nTexnika: {category}\n{specs}\nMarka: {brand}\nRaqam: {plate}\nNarx: {price} so'm/soat\n\n«Ishni boshlash»ni bosing. Taymer faqat ikkala tomon tasdiqlagandan keyin boshlanadi.",
"complete_owner":"Ish haqiqatan tugagan bo'lsa, quyidagi tugmani bosing.","complete_customer":"Ish haqiqatan tugagan bo'lsa, tugashini tasdiqlang.","completion_wait":"Tasdiqlashingiz saqlandi. Ikkinchi tomon tasdig'ini kutmoqdamiz.","order_completed":"<b>#{id} buyurtma to'liq yakunlandi.</b>\n\nIkkala tomon tasdiqladi. Texnika yana bo'sh.",
"start_confirmed":"Ishni boshlash tasdig'ingiz saqlandi. Ikkinchi tomon tasdig'ini kutmoqdamiz.",
"start_wait":"#{id} buyurtma: ikkinchi tomon «Ishni boshlash»ni bosishi kerak.\nTaymer hali ishga tushmagan.",
"work_started":"<b>#{id} buyurtma bo'yicha ish boshlandi.</b>\nNarx: {price} so'm/soat\n\n⏱ Taymer ishga tushdi. Ish tugagach, ikkala tomon «Obyektni tugatish»ni bosadi.",
"timer_live":"<b>#{id} — ish davom etmoqda</b>\n\n⏱ Haqiqiy vaqt: <b>{elapsed}</b>\n💰 Joriy qiymat: <b>{amount} so'm</b>\nNarx: {price} so'm/soat",
"work_finished":"<b>#{id} buyurtma: ish tugadi.</b>\n\n⏱ Haqiqiy vaqt: <b>{elapsed}</b>\nNarx: {price} so'm/soat\n💰 Ish qiymati: <b>{amount} so'm</b>\n📊 Servis komissiyasi 5%: <b>{commission} so'm</b>",
"card_payment":"<b>#{id} buyurtma to'lovi</b>\n\nTo'lash kerak: <b>{amount} so'm</b>\nQabul qiluvchi: <b>{recipient}</b>\nKarta: <code>{card}</code>\n\nO'tkazmadan keyin botga to'lov qilganingizni bildiring.",
"enter_owner_card":"Texnikangiz uchun mijozlar to'lov qiladigan karta raqamini kiriting. Faqat 12–19 ta raqam.",
"card_error":"To'g'ri karta raqamini kiriting (12–19 raqam).",
"owner_payment_blocked":"Yangi buyurtmalar mavjud emas: servis komissiyangiz to'lanmagan. Avval komissiyani to'lang.",
"owner_card_required":"Karta orqali to'lovli buyurtmalar uchun avval egasining kartasini tizimga kiriting.",
"customer_payment_card":"<b>#{id} buyurtma to'lovi</b>\n\nTo'lash kerak: <b>{amount} so'm</b>\nTexnika egasining kartasi: <code>{card}</code>\n\nKo'rsatilgan summani egaga o'tkazing va «To'ladim» tugmasini bosing.",
"customer_payment_cash":"<b>#{id} buyurtma to'lovi</b>\n\nNaqd to'lash kerak: <b>{amount} so'm</b>\n\nPulni haydovchiga bering va «To'ladim» tugmasini bosing.",
"customer_payment_missing_card":"Texnika egasining kartasi ko'rsatilmagan. To'lov uchun yordam xizmatiga murojaat qiling.",
"owner_waiting_payment":"#{id} buyurtma yakunlandi.\n\nQiymat: <b>{amount} so'm</b>\n\n⏳ Buyurtmachining to'lov tasdig'ini kutmoqdamiz.",
"owner_confirm_payment":"Buyurtmachi #{id} buyurtma uchun to'lov qilganini tasdiqladi.\n\nSumma: <b>{amount} so'm</b>\n\nPulni haqiqatan olgan bo'lsangiz, tasdiqlang.",
"customer_payment_sent":"To'lov tasdig'ingiz egaga yuborildi. Uning to'lovni olganini tasdiqlashini kuting.",
"customer_payment_confirmed":"#{id} buyurtma to'lovi ikki tomon tomonidan tasdiqlandi.",
"owner_commission_due":"#{id} buyurtma to'lovi tasdiqlandi.\n\nServis komissiyangiz: <b>{commission} so'm</b> (5%).\n\nServis kartasiga o'tkazing:\nQabul qiluvchi: <b>{recipient}</b>\nKarta: <code>{card}</code>\n\nO'tkazgandan so'ng «Komissiyani to'ladim»ni bosing. Administrator tasdiqlamaguncha yangi buyurtmalar mavjud emas.",
"commission_paid_ok":"Komissiya administrator tomonidan tasdiqlandi. Yangi buyurtmalar yana mavjud.",
"commission_wait_admin":"Komissiya to'lovi administrator tekshiruviga yuborildi. Tasdiqlanguncha yangi buyurtmalar mavjud emas.",
"commission_rejected":"Administrator komissiya to'lovini tasdiqlamadi. O'tkazmani tekshirib, qayta to'lang.",
"admin_customer_payment":"🔔 <b>#{id} buyurtma to'lovini tekshirish</b>\n\nSumma: <b>{amount} so'm</b>\nBuyurtmachi: <code>{customer}</code>\nUsul: {method}",
"customer_payment_rejected":"#{id} buyurtma to'lovi administrator tomonidan tasdiqlanmadi. <b>{amount} so'm</b> to'lovni tekshirib, qayta tasdiqlang.",
"admin_commission":"💳 <b>#{id} komissiya to'lovini tekshirish</b>\n\nHaydovchi: <code>{owner}</code>\nKomissiya: <b>{commission} so'm</b>\nServis kartasi: <code>{card}</code>",
"payment_unavailable":"Bu to'lovni hozir tasdiqlab bo'lmaydi.",
"commission_unavailable":"Komissiyani hozir tasdiqlab bo'lmaydi.",
"cash_commission":"#{id} buyurtma naqd to'landi.\n\nIsh qiymati: {amount} so'm\nServis komissiyasi (5%): <b>{commission} so'm</b>\n\nIltimos, servis komissiyasini o'tkazing.",
"equipment_freed":"Texnika yana bo'sh.","no_orders":"Hozircha buyurtmalar yo'q.","my_orders_title":"<b>Buyurtmalarim</b>\n\n","order_list_item":"#{id} • {category} • {status} • {date_time}\n",
"profile":"<b>Profil</b>\n\nIsm: {name}\nTelegram ID: <code>{telegram_id}</code>\nTelefon: <code>{phone}</code>","support":"Yordam: loyiha administratoriga murojaat qiling.",
"owner_card_saved":"Karta saqlandi. Endi buyurtmachilar ish haqini shu kartaga to'lashlari mumkin.",
"owner_card_title":"<b>Texnika egasining kartasi</b>\n\nJoriy karta: <code>{card}</code>",
"owner_intro":"<b>Texnika egasi kabineti</b>\n\nTexnikangizni qo'shing. Administrator tekshirganidan keyin mos buyurtmalarni oladi.","owner_choose":"Texnika turini tanlang:","enter_brand":"Marka va modelni kiriting.","enter_plate":"Davlat raqamini kiriting.","enter_year":"Ishlab chiqarilgan yilni kiriting.","year_error":"To'g'ri yil kiriting.","enter_price":"Bir soatlik narxni so'mda kiriting.","price_error":"Narxni raqam bilan kiriting.","equipment_added":"#{id} texnika administrator tekshiruviga yuborildi.",
"my_equipment_title":"<b>Mening texnikam</b>\n\n","equipment_item":"#{id} • {category}\nMarka: {brand}\nRaqam: {plate}\n{specs}\nNarx: {price} so'm/soat\nHolat: {status} | Tekshiruv: {verification}\n\n",
"admin_panel":"<b>Admin panel</b>\n\nTekshiruvdagi texnika: {count}","admin_equipment":"<b>Tekshiruvdagi texnika</b>\n\n#{id} • {category}\nMarka: {brand}\nRaqam: {plate}\nEgasi: <code>{owner}</code>\n{specs}\nNarx: {price} so'm/soat","approved":"#{id} texnika tasdiqlandi.","rejected":"#{id} texnika rad etildi.","equipment_approved_owner":"<b>#{id} texnika tasdiqlandi.</b> Mos buyurtmalarni olishi mumkin.","equipment_rejected_owner":"#{id} texnika tekshiruvdan o'tmadi.","flow_cancelled":"Amal bekor qilindi.","session_expired":"Sessiya tugadi. Qaytadan boshlang.","no_pending":"Tekshiruvda texnika yo'q."
}}
def t(k,l="ru"): return TEXTS.get(l,TEXTS["ru"]).get(k,k)

SCHEMAS={
"Бетономиксер":[("drum_volume","Объём барабана","м³")],
"Автобетононасос":[("boom_length","Длина стрелы","м")],
"Самосвал":[("body_volume","Объём кузова","м³"),("payload","Грузоподъёмность","т")],
"Манипулятор":[("lift_capacity","Грузоподъёмность","т"),("reach","Вылет стрелы","м")],
"Экскаватор":[("bucket_volume","Объём ковша","м³")],
"Автокран":[("lift_capacity","Грузоподъёмность","т"),("boom_length","Длина стрелы","м")]
}
UZ={"drum_volume":"Baraban hajmi","boom_length":"Strela uzunligi","body_volume":"Kuzov hajmi","payload":"Yuk ko'tarish","lift_capacity":"Yuk ko'tarish","reach":"Strela chiqishi","bucket_volume":"Kovsh hajmi"}
def schema(cat): return SCHEMAS.get(cat,[])
def label_for(key,lang):
    for k,l,u in sum([v for v in SCHEMAS.values()],[]): 
        if k==key:return UZ.get(key,l) if lang=="uz" else l
def format_specs(cat,specs,lang="ru"):
    out=[]
    for key,label,unit in schema(cat):
        if key in specs: out.append(f"{label_for(key,lang)}: <b>{specs[key]} {unit}</b>")
    return "\n".join(out)
